// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/v1/pager.proto

package pager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_proto_v1_pager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_pager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_pager_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_proto_v1_pager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_pager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_pager_proto_rawDescGZIP(), []int{1}
}

func (x *LoginUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_v1_pager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_pager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_pager_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_v1_pager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_pager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_pager_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SendMessageRequest) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DeliveryToServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	From          int32                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryToServerResponse) Reset() {
	*x = DeliveryToServerResponse{}
	mi := &file_proto_v1_pager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryToServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryToServerResponse) ProtoMessage() {}

func (x *DeliveryToServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_pager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryToServerResponse.ProtoReflect.Descriptor instead.
func (*DeliveryToServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_pager_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryToServerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeliveryToServerResponse) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *DeliveryToServerResponse) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *DeliveryToServerResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DeliveryToServerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UserListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRequest) Reset() {
	*x = UserListRequest{}
	mi := &file_proto_v1_pager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRequest) ProtoMessage() {}

func (x *UserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_pager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRequest.ProtoReflect.Descriptor instead.
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_pager_proto_rawDescGZIP(), []int{5}
}

func (x *UserListRequest) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_v1_pager_proto protoreflect.FileDescriptor

const file_proto_v1_pager_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/pager.proto\x12\x05pager\"[\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"D\n" +
	"\x10LoginUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"R\n" +
	"\x12SendMessageRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02to\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x80\x01\n" +
	"\x18DeliveryToServerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x05R\x02to\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"'\n" +
	"\x0fUserListRequest\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total2\x9c\x02\n" +
	"\x05Pager\x12A\n" +
	"\fRegisterUser\x12\x1a.pager.RegisterUserRequest\x1a\x13.pager.UserResponse\"\x00\x12;\n" +
	"\tLoginUser\x12\x17.pager.LoginUserRequest\x1a\x13.pager.UserResponse\"\x00\x12F\n" +
	"\x13ListRegisteredUsers\x12\x16.pager.UserListRequest\x1a\x13.pager.UserResponse\"\x000\x01\x12K\n" +
	"\vSendMessage\x12\x19.pager.SendMessageRequest\x1a\x1f.pager.DeliveryToServerResponse\"\x00B!Z\x1fgithub.com/andrewizmaylov/pagerb\x06proto3"

var (
	file_proto_v1_pager_proto_rawDescOnce sync.Once
	file_proto_v1_pager_proto_rawDescData []byte
)

func file_proto_v1_pager_proto_rawDescGZIP() []byte {
	file_proto_v1_pager_proto_rawDescOnce.Do(func() {
		file_proto_v1_pager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_pager_proto_rawDesc), len(file_proto_v1_pager_proto_rawDesc)))
	})
	return file_proto_v1_pager_proto_rawDescData
}

var file_proto_v1_pager_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_v1_pager_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),      // 0: pager.RegisterUserRequest
	(*LoginUserRequest)(nil),         // 1: pager.LoginUserRequest
	(*UserResponse)(nil),             // 2: pager.UserResponse
	(*SendMessageRequest)(nil),       // 3: pager.SendMessageRequest
	(*DeliveryToServerResponse)(nil), // 4: pager.DeliveryToServerResponse
	(*UserListRequest)(nil),          // 5: pager.UserListRequest
}
var file_proto_v1_pager_proto_depIdxs = []int32{
	0, // 0: pager.Pager.RegisterUser:input_type -> pager.RegisterUserRequest
	1, // 1: pager.Pager.LoginUser:input_type -> pager.LoginUserRequest
	5, // 2: pager.Pager.ListRegisteredUsers:input_type -> pager.UserListRequest
	3, // 3: pager.Pager.SendMessage:input_type -> pager.SendMessageRequest
	2, // 4: pager.Pager.RegisterUser:output_type -> pager.UserResponse
	2, // 5: pager.Pager.LoginUser:output_type -> pager.UserResponse
	2, // 6: pager.Pager.ListRegisteredUsers:output_type -> pager.UserResponse
	4, // 7: pager.Pager.SendMessage:output_type -> pager.DeliveryToServerResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_pager_proto_init() }
func file_proto_v1_pager_proto_init() {
	if File_proto_v1_pager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_pager_proto_rawDesc), len(file_proto_v1_pager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_pager_proto_goTypes,
		DependencyIndexes: file_proto_v1_pager_proto_depIdxs,
		MessageInfos:      file_proto_v1_pager_proto_msgTypes,
	}.Build()
	File_proto_v1_pager_proto = out.File
	file_proto_v1_pager_proto_goTypes = nil
	file_proto_v1_pager_proto_depIdxs = nil
}
