// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/v1/pager.proto

package pagerv01

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Pager_RegisterUser_FullMethodName        = "/pager.Pager/RegisterUser"
	Pager_LoginUser_FullMethodName           = "/pager.Pager/LoginUser"
	Pager_ListRegisteredUsers_FullMethodName = "/pager.Pager/ListRegisteredUsers"
	Pager_SendMessage_FullMethodName         = "/pager.Pager/SendMessage"
)

// PagerClient is the client API for Pager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PagerClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	ListRegisteredUsers(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserResponse], error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*DeliveryToServerResponse, error)
}

type pagerClient struct {
	cc grpc.ClientConnInterface
}

func NewPagerClient(cc grpc.ClientConnInterface) PagerClient {
	return &pagerClient{cc}
}

func (c *pagerClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, Pager_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagerClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, Pager_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagerClient) ListRegisteredUsers(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UserResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Pager_ServiceDesc.Streams[0], Pager_ListRegisteredUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UserListRequest, UserResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pager_ListRegisteredUsersClient = grpc.ServerStreamingClient[UserResponse]

func (c *pagerClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*DeliveryToServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryToServerResponse)
	err := c.cc.Invoke(ctx, Pager_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagerServer is the server API for Pager service.
// All implementations must embed UnimplementedPagerServer
// for forward compatibility.
type PagerServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*UserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	ListRegisteredUsers(*UserListRequest, grpc.ServerStreamingServer[UserResponse]) error
	SendMessage(context.Context, *SendMessageRequest) (*DeliveryToServerResponse, error)
	mustEmbedUnimplementedPagerServer()
}

// UnimplementedPagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPagerServer struct{}

func (UnimplementedPagerServer) RegisterUser(context.Context, *RegisterUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedPagerServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedPagerServer) ListRegisteredUsers(*UserListRequest, grpc.ServerStreamingServer[UserResponse]) error {
	return status.Error(codes.Unimplemented, "method ListRegisteredUsers not implemented")
}
func (UnimplementedPagerServer) SendMessage(context.Context, *SendMessageRequest) (*DeliveryToServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedPagerServer) mustEmbedUnimplementedPagerServer() {}
func (UnimplementedPagerServer) testEmbeddedByValue()               {}

// UnsafePagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PagerServer will
// result in compilation errors.
type UnsafePagerServer interface {
	mustEmbedUnimplementedPagerServer()
}

func RegisterPagerServer(s grpc.ServiceRegistrar, srv PagerServer) {
	// If the following call panics, it indicates UnimplementedPagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pager_ServiceDesc, srv)
}

func _Pager_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagerServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pager_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagerServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pager_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagerServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pager_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagerServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pager_ListRegisteredUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PagerServer).ListRegisteredUsers(m, &grpc.GenericServerStream[UserListRequest, UserResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Pager_ListRegisteredUsersServer = grpc.ServerStreamingServer[UserResponse]

func _Pager_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pager_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagerServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pager_ServiceDesc is the grpc.ServiceDesc for Pager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pager.Pager",
	HandlerType: (*PagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _Pager_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Pager_LoginUser_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Pager_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListRegisteredUsers",
			Handler:       _Pager_ListRegisteredUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/pager.proto",
}
